#!/bin/bash

## Get battery info
CHARGE="$(upower -i $(upower -e | grep 'BAT') | grep -E  'state' | awk -F ':' 'NR==1 {print $2}' | xargs)"
BATTERY="$(upower -i $(upower -e | grep 'BAT') | grep -E 'percentage' | awk -F ':' 'NR==1 {print $2}' | tr -d \%, | xargs)"

main() {
	if [[ ($CHARGE = "charging") && ($BATTERY -lt 100) ]]; then
		echo "images/icons/battery/charge.png"
	elif [[ $CHARGE = *"fully-charged"* || ($BATTERY -eq 100) ]]; then
		echo "images/icons/battery/full.png"
	else
		if [[ ($BATTERY -lt 100) && ($BATTERY -ge 65) ]]; then
			echo "images/icons/battery/battery-3.png"
		elif [[ ($BATTERY -lt 65) && ($BATTERY -ge 35) ]]; then
			echo "images/icons/battery/battery-2.png"
		elif [[ ($BATTERY -lt 35) && ($BATTERY -ge 10) ]]; then
			echo "images/icons/battery/battery-1.png"
		elif [[ ($BATTERY -lt 10) && ($BATTERY -ge 0) ]]; then
			echo "images/icons/battery/low.png"
		fi
	fi
}

if [[ $1 == '--icon' ]]; then
	main
elif [[ $1 == '--perc' ]]; then
	echo "${BATTERY}%"
fi
