#!/bin/bash

# Get Volume
get_brightness() {
  brightness=`brightnessctl g`
  max=`brightnessctl m`
  ratio=`expr "$max" / 100`
  percent=`expr "$brightness" / "$ratio"`
  
	echo "$percent"
}

# Execute accordingly
get_brightness
