#!/bin/bash

WIFI="disconnected"
ETHERNET="disconnected"
VPN="disconnected"

initialize () {
    for i in $(nmcli -f type c show --active) ; do
      if [ "$i" = "vpn" ]; then
        VPN="connected"
      elif [ "$i" = "wifi" ]; then
        WIFI="connected"
      elif [ "$i" = "ethernet" ];then
        ETHERNET="connected"
      fi
    done
}

parse_output () {
   interface=$(echo "$1" | awk -F ':' '{print $1;}' )
   status=$(echo "$1" | awk -F ':' '{gsub(/ /, "", $0);print $2}' | awk -F '(' '{print $1}' )

   if [ "$interface" = "wlan0" ]; then
     WIFI="$status"
   elif [ "$interface" = "vpn0" ]; then
     if [ "$status" = "connected" ]; then
      VPN="$status"
     elif [ "$status" = "connectionprofileremoved" ]; then
      VPN="disconnected"
     fi
   fi

   if [ "$VPN" = "connected" ]; then
     if [ "$ETHERNET" = "connected" ]; then
       echo "images/icons/system/locked.png"
     elif [ "$WIFI" = "connected" ]; then
       echo "images/icons/system/locked.png"
     fi
   else
     if [ "$ETHERNET" = "connected" ]; then
       echo "images/icons/system/ethernet.png"
     elif [ "$WIFI" = "connected" ]; then
       echo "images/icons/system/wifi.png"
     else
       echo "images/icons/system/no-wifi.png"
     fi
   fi
}


monitor () {
  nmcli m  | while read -r line; do
	   parse_output "$line"
  done
}


initialize
monitor

