#!/bin/bash

if [[ "$1" == "--tr" ]]; then
	kitty --working-directory ~ &

elif [[ "$1" == "--ff" ]]; then
	firefox &

elif [[ "$1" == "--fm" ]]; then
	thunar ~ &

elif [[ "$1" == "--ge" ]]; then
  kitty -e nvim &

elif [[ "$1" == "--gh" ]]; then
	firefox --new-tab "https://github.com"

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &

elif [[ "$1" == "--rd" ]]; then
	firefox --new-tab "https://reddit.com"

elif [[ "$1" == "--ml" ]]; then
	swaync-client -t 

elif [[ "$1" == "--nm" ]]; then
	networkmanager_dmenu

fi
