set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-yank'

# Optional configurations with their default values if omitted:

set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)

set -g @smart-splits_move_left_key  'C-left' # key-mapping for navigation.
set -g @smart-splits_move_down_key  'C-down' #  --"--
set -g @smart-splits_move_up_key    'C-up' #  --"--
set -g @smart-splits_move_right_key 'C-right' #  --"--

set -g @smart-splits_resize_left_key  'M-left' # key-mapping for resizing.
set -g @smart-splits_resize_down_key  'M-down' #  --"--
set -g @smart-splits_resize_up_key    'M-up' #  --"--
set -g @smart-splits_resize_right_key 'M-right' #  --"--

# Configure Catppuccin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"


# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=default,bold]  #S },#{#[bg=default,fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=default,fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=default,fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right-length 100
set -g status-right ""

# bootstrap tpm
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
# Extended keys
set -s extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features 'xterm-kitty:extkeys'
# Configure Tmux
set -g status-position top
set -g status-style "bg=default"
set -g status-justify "absolute-centre"

# pane border look and feel
setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-active-border-style "bg=default,fg=#{@thm_pink}"
setw -g pane-border-style "bg=default,fg=#{@thm_pink}" 
setw -g pane-border-lines single

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=default,fg=#{@thm_rosewater}"
set -g window-status-last-style "bg=default,fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=default"
set -g window-status-bell-style "bg=#{@thm_red},fg=default,bold"
set -gF window-status-separator "#[bg=default,fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_peach},fg=black,bold"

setw -g mouse on

set -g mode-keys vi

bind -n M-t new-window -c "#{pane_current_path}"
bind -n M-n split-window -h -c "#{pane_current_path}"
bind -n M-v split-window -v -c "#{pane_current_path}"
bind -n M-d kill-pane
bind -n M-[ select-window -t -1
bind -n M-] select-window -t +1

