#!/bin/bash

EWW=`which eww`
CFG="$HOME/.config/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi


## Open widgets 
run_eww() {
	ids=$( hyprctl monitors -j | jq -r @sh )
	for i in "${!ids[@]}"  
	do
		echo "$i"
		${EWW} --config "$CFG" open \
		   	 top_bar_"$i" 
		
		${EWW} --config "$CFG"/sidebar/"$i" open \
		   	 left_bar 
	done
}

## Launch or close widgets accordingly
run_eww
