#!/bin/bash

EWW=`which eww`
CFG="$HOME/.config/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi


## Open widgets 
run_eww() {
	for monitor in $( hyprctl monitors -j | jq  '[.[] | .id]' | jq -r @sh ) 
	do
		${EWW} --config "$CFG" open \
		   	 top_bar_"$monitor" 
		
		${EWW} --config "$CFG"/sidebar/"$monitor" open \
		   	 left_bar 
	done
}

## Launch or close widgets accordingly
run_eww
