# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
general {
  layout = scrolling
}

input {
    kb_layout = us
    kb_variant = altgr-intl
}
