# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Uncomment to apply global transparency to all windows:
windowrulev2 = opacity 0.87 override 0.87 override, class:.*
