
unbind = Super, Period
unbind = Super, V
unbind = Super, D
unbind = Super, Q
unbind = Super, L
unbind = Super, K
unbind = Super, H
unbind = Super, J
unbind = Super, G
unbind = Super, W
unbind = Super, N
unbind = Super, M
unbind = Super, R
unbind = Super, left
unbind = Super, right
unbind = Super, up
unbind = Super, down
unbind = Super+Shift, left
unbind = Super+Shift, right
unbind = Super+Shift, up
unbind = Super+Shift, down

bind = Super, V, exec, walker -m clipboard
bind = Super, Period, exec, walker -m symbols
bind = Super, H, exec, caelestia shell drawers toggle sidebar
bind = Super, D, exec, caelestia shell drawers toggle dashboard
bind = Super, K, exec, caelestia toggle music
bind = SUPER, g, hyprexpo:expo, toggle

bind = Super, left, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus l || hyprctl dispatch hy3:movefocus l
bind = Super, right, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus r || hyprctl dispatch hy3:movefocus r
bind = Super, up, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus u || hyprctl dispatch hy3:movefocus u
bind = Super, down, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus d || hyprctl dispatch hy3:movefocus d
bind = Super+Shift, left, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus l || hyprctl dispatch hy3:movewindow l
bind = Super+Shift, right, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus r || hyprctl dispatch hy3:movewindow r
bind = Super+Shift, up, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus u || hyprctl dispatch hy3:movewindow u
bind = Super+Shift, down, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl dispatch layoutmsg focus d || hyprctl dispatch hy3:movewindow d
bind = Super+Shift, Q, killactive, 
bind = Super+Shift+Alt, Q, exec, hyprctl kill 
bind = Super, R, exec, hyprctl getoption general:layout | grep -q 'scrolling' && hyprctl keyword general:layout hy3 || hyprctl keyword general:layout scrolling

bind = Super, W, fullscreen, 1 

exec-once = /usr/bin/caelestia shell -d
exec-once = sleep 1 && /opt/forticlient/start-fortitray-launcher.sh
exec-once = sleep 1 && /usr/bin/ktailctl
exec-once = /usr/bin/hyprshell run &
exec-once = /usr/bin/elephant &
exec-once = /usr/bin/walker --gapplication-service
exec-once = hyprpm reload -n
exec-once = /usr/bin/supersonic-desktop 
exec-once = /usr/bin/ferdium & hyprctl dispatch movetoworkspacesilent special:communication,class:ferdium

source = ~/.config/hypr/monitors.conf
# Trigger when the switch is toggled.
# bindl = , switch:Lid Switch, exec, swaylock
# Trigger when the switch is turning on.
bindl = , switch:on:Lid Switch, exec, /home/brunnseb/.config/caelestia/close-lid.sh
# Trigger when the switch is turning off.
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 1920x1200, 0x0, 1"
### Lid is opened
#bindl=,switch:off:Lid Switch,exec,~/.config/caelestia/clamshell-mode.sh open
#
### Lid is closed
#bindl=,switch:on:Lid Switch,exec,~/.config/caelestia/clamshell-mode.sh close


general {
    layout = hy3
}

input {
    kb_layout = us, us
    kb_variant = altgr-intl, colemak_dh
    kb_options = grp:ctrl_space_toggle
}
