$kbLock = Super, Escape
$kbCommunication = Super, A
$terminal = wezterm
$browser = firefox
$kbTerminal = Super, Return
$kbBrowser = Super, C
$kbMoveWinToWs = Super+Shift
$kbMoveWinToWsGroup = Ctrl+Super+Shift
$kbToggleWindowFloating = Alt, Space
# Gaps
$workspaceGaps = 10
$windowGapsIn = 8
$windowGapsOut = 10
$singleWindowGapsOut = 10
