
unbind = Super, Period
unbind = Super, V
unbind = Super, D
unbind = Super, Q
unbind = Super, L
unbind = Super, K
unbind = Super, H
unbind = Super, J
unbind = Super, G
unbind = Super, W
unbind = Super, N
unbind = Super, M
unbind = Super, R
unbind = Super, S
unbind = Super, left
unbind = Super, right
unbind = Super, up
unbind = Super, down
unbind = Super+Shift, left
unbind = Super+Shift, right
unbind = Super+Shift, up
unbind = Super+Shift, down
unbind = Super+Shift,A
unbind = Super, Super_L,
unbind = Super, catchall,
unbind = Super, mouse:272
unbind = Super, mouse:273
unbind = Super, mouse:274
unbind = Super, mouse:275
unbind = Super, mouse:276
unbind = Super, mouse:277
unbind = Super, mouse_up 
unbind = Super, mouse_down

bind = Super,Super_L, exec, walker
bind = Super, V, exec, walker -m clipboard
bind = Super, Period, exec, walker -m symbols
bind = Super, H, exec, caelestia shell drawers toggle sidebar
bind = Super, D, exec, caelestia shell drawers toggle dashboard
bind = Super, K, exec, caelestia toggle music
bind = SUPER, g, hyprexpo:expo, toggle

bind = Super, left, exec,  hyprctl dispatch layoutmsg focus l 
bind = Super, right, exec,  hyprctl dispatch layoutmsg focus r 
bind = Super, up, exec,  hyprctl dispatch layoutmsg focus u 
bind = Super, down, exec,  hyprctl dispatch layoutmsg focus d
bind = Super+Shift, left, exec,  hyprctl dispatch layoutmsg swapcol l
bind = Super+Shift, right, exec,  hyprctl dispatch layoutmsg swapcol r
bind = Alt+Shift, left, exec,  hyprctl dispatch layoutmsg movewindowto l
bind = Alt+Shift, right, exec,  hyprctl dispatch layoutmsg movewindowto r
bind = Alt+Shift, up, exec,  hyprctl dispatch layoutmsg movewindowto u
bind = Alt+Shift, down, exec,  hyprctl dispatch layoutmsg movewindowto d
bind = Super+Alt+Shift, left, exec, hyprctl dispatch split-changemonitor prev
bind = Super+Alt+Shift, right, exec, hyprctl dispatch split-changemonitor next
bind = Super+Alt, left, exec, hyprctl dispatch focusmonitor -1
bind = Super+Alt, right, exec, hyprctl dispatch focusmonitor +1
bind = Super+Shift, Q, killactive, 
bind = Super+Shift+Alt, Q, exec, hyprctl kill 
bind = Super, R, exec,  hyprctl keyword general:layout hy3 || hyprctl keyword general:layout scrolling
bind = Super+Shift, A, exec, hyprctl activewindow -j | jq -e '.workspace.id > 0' &&  hyprctl dispatch movetoworkspacesilent special:communication || hyprctl dispatch movetoworkspacesilent +0
bind = Super, B, exec, hyprctl dispatch layoutmsg togglefit
bind = Super, MINUS, exec, hyprctl dispatch layoutmsg colresize +conf

bind = Super, W, fullscreen, 1 

exec-once = sleep 1 && /opt/forticlient/start-fortitray-launcher.sh
exec-once = sleep 1 && /usr/bin/ktailctl
exec-once = /usr/bin/elephant &
exec-once = /usr/bin/walker --gapplication-service
exec-once = hyprpm reload -n
exec-once = /usr/bin/supersonic-desktop 
# exec-once = /usr/bin/ferdium  

source = ~/.config/hypr/monitors.conf
# Trigger when the switch is toggled.
# bindl = , switch:Lid Switch, exec, swaylock
# Trigger when the switch is turning on.
bindl = , switch:on:Lid Switch, exec, /home/brunnseb/.config/caelestia/close-lid.sh
# Trigger when the switch is turning off.
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 1920x1200, 0x0, 1"
### Lid is opened
#bindl=,switch:off:Lid Switch,exec,~/.config/caelestia/clamshell-mode.sh open
#
### Lid is closed
#bindl=,switch:on:Lid Switch,exec,~/.config/caelestia/clamshell-mode.sh close
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

general {
    layout = scrolling
}


plugin {
    hyprscrolling {
        fullscreen_on_one_column = true
    }
}

input {
    kb_layout = us, us
    kb_variant = altgr-intl, colemak_dh
    kb_options = grp:ctrl_space_toggle
}
