#! /bin/bash
CURRENT_WORKSPACE=`hyprctl activewindow | grep 'workspace' | awk 'NR==2 {print $2}'`
CURRENT_MONITOR=$(hyprctl monitors -j | jq '.[] | select( .focused == true ) | .id')
MULTIPLIER="$(( 10 * $CURRENT_MONITOR ))"
MULTIPLIER=0

MIN=`expr 1 + $MULTIPLIER`
MAX=`expr 10 + $MULTIPLIER`

if [ "$1" = "prev" ]; then
  if [ "$CURRENT_WORKSPACE" -eq 1 ]; then
    echo "$MAX"
    hyprctl dispatch workspace 10
  else
    hyprctl dispatch workspace -1
  fi
else
  if [ "$CURRENT_WORKSPACE" -eq 10 ]; then
    echo "$MIN"
    hyprctl dispatch workspace 1
  else
    hyprctl dispatch workspace  +1
  fi
fi




