#!/bin/zsh

TARGET="area"
if [[ "$1" == "active" ]]; then
	TARGET=$1
fi

if [[ "$1" == "output" ]]; then
	TARGET=$1
fi

FNAME="$(date +'%s').png"
TMP_DIR="/tmp/swappy/$FNAME"
mkdir -p $(dirname "$TMP_DIR")
grimblast --notify copysave $TARGET "$TMP_DIR"
swappy -f "$TMP_DIR" -o "/home/brunnseb/Pictures/screenshots/$FNAME" &
