#!/bin/bash

## Files and CMD
FILE="$HOME/.cache/eww_launch.sidebar"
CFG="$HOME/.config/eww/arin/sidedar"
EWW=`which eww`


if [[ -f "$FILE" ]]; then
	${EWW} --config "$CFG" close resources 
	rm "$FILE"
fi
