#!/bin/bash

## Files and CMD
FILE="$HOME/.cache/eww_launch.sidebar"
CFG="$HOME/.config/eww/arin/sidedar"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	monitor=$( hyprctl monitors -j | jq  '.[] | select(.focused = true) | .id'  )
	${EWW} --config "$CFG" open \
			resources \
			--screen "$monitor"
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close resources 
	rm "$FILE"
fi
