#!/bin/bash

## Files and CMD
FILE="$HOME/.cache/eww_launch.user-menu"
CFG="$HOME/.config/eww/user-menu"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	monitor=$( hyprctl monitors -j | jq  '.[] | select(.focused == true) | .id'  )
	echo "$monitor"
	swaync-client -cp
	${EWW} --config "$CFG" open \
			user-menu_"$monitor" 
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close user-menu_0 user-menu_1 user-menu_2 
	rm "$FILE"
fi
