#!/bin/bash

## Get battery info
CHARGE="$( upower -i $(upower -e | grep 'BAT') | grep -E  'state|to full|percentage' | awk -F ':' 'NR==1 {print $2}')"
BATTERY="$(upower -i $(upower -e | grep 'BAT') | grep -E 'state|to full|percentage' | awk -F ':' 'NR==2 {print $2}' | tr -d \%,)"

main() {
	if [[ ($CHARGE = *"charging"*) && ($BATTERY -lt "100") ]]; then
		echo "images/icons/battery/charge.png"
	elif [[ $CHARGE = *"fully-charged"* ]]; then
		echo "images/icons/battery/full.png"
	else
		if [[ ($BATTERY -lt 100) && (($BATTERY -gt 65) || ($BATTERY -eq 65)) ]]; then
			echo "images/icons/battery/battery-3.png"
		elif [[ ($BATTERY -lt 65) && (($BATTERY -gt 35) || ($BATTERY -eq 35)) ]]; then
			echo "images/icons/battery/battery-2.png"
		elif [[ ($BATTERY -lt 35) && (($BATTERY -gt 10) || ($BATTERY -eq 10)) ]]; then
			echo "images/icons/battery/battery-1.png"
		elif [[ ($BATTERY -lt 10) && (($BATTERY -gt 0) || ($BATTERY -eq 0)) ]]; then
			echo "images/icons/battery/low.png"
		fi
	fi
}

if [[ $1 == '--icon' ]]; then
	main
elif [[ $1 == '--perc' ]]; then
	echo "${BATTERY}%"
fi
