#!/bin/bash

spaces (){
  CURRENT_MONITOR=$(hyprctl monitors -j | jq --arg MONITOR $1 '.[] | select( .id == $MONITOR ) | .name')
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq --arg CURRENT_MONITOR "$CURRENT_MONITOR" '[.[] | select( .monitor == "$CURRENT_MONITOR" )] | map({key: .id | tostring, value: .windows}) | from_entries')
	MULTIPLIER="$(( 10 * $1 ))"
	MIN=`expr 1 + $MULTIPLIER`
	MAX=`expr 10 + $MULTIPLIER`
	seq "$MIN" "$MAX" | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces $1
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^workspace>>'| while read -r line; do
	spaces $1
done
