#!/bin/bash

# Get Volume
get_volume() {
	mute=`pamixer --get-mute`

	if [[ "$mute" = true ]]; then
		echo "Mute"
	else
		volume=`pamixer --get-volume`
		echo "$volume"
	fi
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	mute=`pamixer --get-mute`

	if [[ "$mute" = true  ]]; then
		echo "images/icons/volume/mute.png"
	else
		if [[ "$current" -eq "0" ]]; then
			echo "images/icons/volume/mute.png"
		elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
			echo "images/icons/volume/volume.png"
		elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
			echo "images/icons/volume/volume.png"
		elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
			echo "images/icons/volume/volume.png"
		fi
	fi
}

# Increase Volume
inc_volume() {
	pamixer --increase 5 --unmute
}

# Decrease Volume
dec_volume() {
	pamixer --decrease 5 --unmute
}

# Toggle Mute
toggle_mute() {
	mute=`pamixer --get-mute`

	if [[ "$mute" = true  ]]; then
		pamixer --unmute
	else
		pamixer --mute
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi
